export const enum entityTypes {
    PAYMENT = "PAYMENT",
    PETTY_CASH = "PETTY_CASH",
    INVOICE = "INVOICE",
    RECEIPTS = "RECEIPTS",
    GOODS_RECEIVED = "GOODS_RECEIVED",
    STOCKS = "STOCKS",
    BANK_TRANSFER = "BANK_TRANSFER",
    PAYROLL = "PAYROLL",
    JOURNALS = "JOURNALS"
};